[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=1
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCode=0
RebootMode=I
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=uninstall.exe
FriendlyName=Universal Copilot Uninstaller
AppLaunched=uninstall_launcher.bat
PostInstallCmd=<None>
AdminChoose=No
ExtractDir=%TEMP%\\UniversalCopilot_uninstall
[SourceFiles]
SourceFiles0=.
[SourceFiles0]
install_launcher.bat=install_launcher.bat
portable_install.ps1=portable_install.ps1
portable_uninstall.ps1=portable_uninstall.ps1
README_INSTALL.md=README_INSTALL.md
run_with_env.ps1=run_with_env.ps1
start-minimized.vbs=start-minimized.vbs
start.bat=start.bat
uninstall_launcher.bat=uninstall_launcher.bat
universal_copilot.exe=universal_copilot.exe
